### ISSUE TITLE
Bing can't be used

### ISSUE THREAD

**Issue by drgenial4** [shigeyukey/Anki-Terminator-#1]
Hello and thank you for this wonderful add-on, gent.

I run into a problem when i try to use the Bing Bing AI. It says, due to my Safesearch being set to "strict", the Ai can not be used. So i decided to change this "strict" setting. But i can't do that because it is automatically set in my country"Switzerland". Do you know about this and is there any alternative to circumvet it?

Thank you forever.

**Comment by shigeyukey** [comment]
Hello, thank you for the feedback!
This issue seems to be Bing's problem, there are many reports of similar issues by Bing users with Edge browser(Bing Reddit, Microsoft Community, etc.). I have not found a workaround for now.
