### ISSUE TITLE
Prompts are not being pre-written in the chat-box

### ISSUE THREAD

**Issue by Aaarkay1** [shigeyukey/Anki-Terminator-#12]
Some bots, including Bing AI,  do not populate chat-box like Gemini or ChatGPT. I recently also used another Custom AI through link and it was also not populating the chat box with front card material. How to fix this?

**Comment by shigeyukey** [comment]
Thanks for reporting the issue! :-)
The feature to auto-input prompts works by manipulating the website directly by code.
Bing AI and Custom AI do not work with such code, so prompts are not available.

I would like to solve this problem in another way. (e.g., right-click and paste the prompt to input it).

**Comment by shigeyukey** [comment]
1. I added a workaround for this problem, I think it works with Bing.

2. This add-on can no longer be updated due to a bug, so I changed it to the new add-on page.
     * new add-on code : 1468920185
     * new addon page : [🤖Anki Terminator V2](https://ankiweb.net/shared/info/1468920185)
