### ISSUE TITLE
i tried adding this custom prompt ... and it doesnot work .. any idea why it is not working ? 

### ISSUE THREAD

**Issue by fredjoe7** [shigeyukey/Anki-Terminator-#2]
i tried adding this custom prompt ... and it doesnot work .. any idea why it is not working ? 
I want you to create a deck of flashcards from the text.

Instructions to create a deck of flashcards:
- Keep the flashcards simple, clear, and focused on the most important information.
- Make sure the questions are specific and unambiguous.
- Use simple and direct language to make the cards easy to read and understand.
- Answers should contain only a single key fact/name/concept/term.

Let's do it step by step when creating a deck of flashcards:
1. Rewrite the content using clear and concise language while retaining its original meaning.
2. Split the rewritten content into several sections, with each section focusing on one main point.
3. Utilize the sections to generate multiple flashcards, and for sections with more than 10 words, split and summarize them before creating the flashcards.

Text: The characteristics of the Dead Sea: Salt lake located on the border between Israel and Jordan. Its shoreline is the lowest point on the Earth's surface, averaging 396 m below sea level. It is 74 km long. It is seven times as salty (30% by volume) as the ocean. Its density keeps swimmers afloat. Only simple organisms can live in its saline waters

A deck of flashcards:
   Question   Answer   

   Where is the Dead Sea located?   on the border between Israel and Jordan   
   What is the lowest point on the Earth's surface?   The Dead Sea shoreline   
   What is the average level on which the Dead Sea is located?   396 meters (below sea level)   
   How long is the Dead Sea?   74 km   
   How much saltier is the Dead Sea as compared with the oceans?   7 times   
   What is the volume content of salt in the Dead Sea?   30%   
   Why can the Dead Sea keep swimmers afloat?   due to high salt content   
   Why is the Dead Sea called Dead?   because only simple organisms can live in it   
   Why only simple organisms can live in the Dead Sea?   because of high salt content   

Text: {}

**Comment by fredjoe7** [comment]
![image](https://github.com/shigeyukey/Anki-Terminator-/assets/107930196/655a54d1-19ad-4e74-bc88-78ca2cf172ee)
nothing happens when i click on the prompt... no autofill working...

**Comment by shigeyukey** [comment]
Perhaps the option "auto input prompts" is disabled?

- Option -> Other tab -> Auto Prompt -> auto input prompts

**Comment by shigeyukey** [comment]
If you have any additional information, please contact me again.
