### ISSUE TITLE
Prompts can't be sent automatically to Bing

### ISSUE THREAD

**Issue by drgenial4** [shigeyukey/Anki-Terminator-#3]
Hi.

The prompts are sent automatically to Bard and chatgpt, but not to Bing. Is there a way around this problem?

**Comment by shigeyukey** [comment]
Hello, thanks for the feedback :-D
BingChat is a bit difficult, probably blocking it from sending automatically.
Besides, compared to ChatGPT, Bing has fewer users, so there is less information.
(ChatGPT and GoogleBard were easy).
If I find a workaround, I will try it.

**Comment by drgenial4** [comment]
True.

Now they introduced Copilot Pro, thankfully without the atrocious 40messages/3hours limit from chagpt. For heavy users, Bingchat makes more sense now. Just saying, :D.

**Comment by shigeyukey** [comment]
That's good news, I've never heard that before. It seems there are more Anki users who want to use Bing than I thought, so I will look into it again.

**Comment by shigeyukey** [comment]
I added a workaround and updated it.

**Comment by BEST8OY** [comment]
@shigeyukey 
Hey shige
Can you make copilot so it doesn't load the url+prompt and be like the other services like chatgpt and others?
As the way it is now, I can't use the deep think feature of copilot
And it would be nice to use Copilot in all places in the code instead of Bing.

**Comment by shigeyukey** [comment]
Yes! I came up with a good workaround last update, so it's probably possible. (Currently I'm checking to see if it works correctly with ImageFX.) I'll try it in the next update.

**Comment by shigeyukey** [comment]
I added it, so far it is working fine on my device.
