### ISSUE TITLE
Auto send prompt for ChatGPT doesn't seem to work

### ISSUE THREAD

**Issue by yougnut** [shigeyukey/Anki-Terminator-#7]
I've also tried manually sending, but the keyboard shortcut doesn't seem to work as well. Would greatly appreciate it if you could spare some time to look into it, thanks.

**Comment by shigeyukey** [comment]
Thanks for the error report, I will upload the fixed version later.

**Comment by shigeyukey** [comment]
I updated. The auto-send is fragile (When they update the page it breaks), so feel free to contact me if it breaks again.
