### ISSUE TITLE
Problems encountered

### ISSUE THREAD

**Issue by skyfox6688** [shigeyukey/Anki-Terminator-#8]
I cannot customize the model. I hope to add it myself. If there are not enough prompts, I hope to add it myself. I am a donating user. Anki supported versions:
2.1.1-24.06+(updated on June 5, 2024) What was updated on June 6.5

**Comment by shigeyukey** [comment]
Thanks for the support and the report.

> I cannot customize the model. i hope to add it myself. 

To use a customized URL, you need to turn on the checkbox.

> If there are not enough prompts, I hope to add it myself. 

This feature has already been requested, but not yet developed. [suggest #6](https://github.com/shigeyukey/Anki-Terminator-/issues/6)

> I am a donating user.

If you have been supporting me for a long time, I may be able to prioritize it over other requests, or release an add-on for Patreon only. I can't confirm from Github, so please contact me via Patreon direct message. Thank you.

**Comment by shigeyukey** [comment]
I think the custom URL is working.
Multiple prompts are addressed in this issue.
https://github.com/shigeyukey/Anki-Terminator-/issues/6
