### ISSUE TITLE
chatgpt

### ISSUE THREAD

**Issue by keen0309** [shigeyukey/Anki-Terminator-#9]
I am using official GPT and cannot allow recording

![image](https://github.com/shigeyukey/Anki-Terminator-/assets/103982843/80f718d8-ffcf-4c6f-9c28-4de40df07c55)

**Comment by shigeyukey** [comment]
Thanks for the report.
I don't know if the microphone feature can be developed, I tried to enable the microphone in the Discord add-on but it was not possible due to limitations of the PyQt that Anki is using.

**Comment by shigeyukey** [comment]
https://github.com/shigeyukey/Anki-Terminator-/issues/10
